### ISSUE TITLE
importing cdf (raw) from Waters

### ISSUE THREAD

**Issue by crestre** [ethanbass/chromConverter#19]
Hi Ethan,

This is a reply to the issue that I opened previously (https://github.com/ethanbass/chromatographR/issues/29).

When exporting from the Waters instrument via their software (Empower) there are two options: 1) ascii (the resulting files have the .arw extension) and 2) raw (the resulting files have the .cdf extension).

**Comment by ethanbass** [comment]
I think you would access the Waters `.raw` files from the file system. You shouldn't have to export them. I don't know off hand where Empower stores the raw data files though. Probably there's a `data` folder or something like that?

**Comment by crestre** [comment]
I followed your instructions and to an error message that reads:
Error in strsplit(ini[cli_index], "=")[[1]] : subscript out of bounds

I will check in the computer that has that software.

**Comment by ethanbass** [comment]
> I followed your instructions and to an error message that reads: Error in strsplit(ini[cli_index], "=")[[1]] : subscript out of bounds

Hmm. This is an issue with the configuration of chromConverter. What OS are you using?

**Comment by crestre** [comment]
I am working on a PC running on Windows 10

**Comment by ethanbass** [comment]
And you're still using the latest version of chromConverter from GitHub? It should be version 0.4.3 if you run `packageVersion("chromConverter")`

**Comment by crestre** [comment]
Yes, that is the library that I am using.

I also tried opening the wt15.CDF from the faakKO library that is used in the library xcms - I get the same message.

**Comment by ethanbass** [comment]
It's not working because apparently OpenChrom recently removed the support for the command line interface (https://github.com/eclipse/chemclipse/issues/1393). You could try downloading the older version of OpenChrom (version 1.4) that still included the command line interface.

**Comment by crestre** [comment]
Thanks a lot!
